# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('band_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('band_description', models.TextField(blank=True, max_length=500)),
                ('band_photo', models.ImageField(blank=True, upload_to='band_photo')),
            ],
        ),
        migrations.CreateModel(
            name='BandEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_time', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(max_length=100)),
                ('song_list', models.TextField(max_length=500)),
                ('poster_photo', models.ImageField(upload_to='poster_photo')),
                ('is_live', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEMPO.Band')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_time', models.DateField(default=datetime.date.today)),
                ('song_list', models.TextField(max_length=500)),
                ('is_live', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('starter', models.CharField(blank=True, max_length=200, null=True)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEMPO.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_photo')),
                ('band', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEMPO.Band')),
                ('subscribe_events', models.ManyToManyField(to='TEMPO.BandEvent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
