# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TEMPO', '0002_auto_20171130_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='band_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TEMPO.BandEvent'),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='music_score',
            field=models.FileField(upload_to='music_score'),
        ),
    ]
