# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEMPO', '0004_auto_20171201_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='song_list',
        ),
    ]
