# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEMPO', '0005_remove_practicesession_song_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_day',
            new_name='birthday',
        ),
    ]
